// Re-export all sidebar components from sub-modules
// Re-export all sidebar components from sub-modules
// Note: we MUST import from ./sidebar/index explicitly to avoid circular self-reference
export {
  SidebarProvider,
  Sidebar,
  SidebarTrigger,
  SidebarRail,
  SidebarInset,
  SidebarInput,
  SidebarHeader,
  SidebarFooter,
  SidebarSeparator,
  SidebarContent,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubItem,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuSkeleton,
  SidebarMenuSubButton,
  sidebarMenuButtonVariants,
  SidebarContext,
  useSidebar,
} from './sidebar/index';
